import { StrategyConfig, BacktestResult, MarketDataResponse, StockProfile, MarketBar, EquityPoint, TradeRecord } from "@/types";

export const SEED_STRATEGIES: StrategyConfig[] = [
  {
    id: "tpl_sma_crossover",
    name: "Dual Moving Average Crossover",
    description: "Classic trend-following strategy that goes long when the fast 20 SMA crosses above the slow 50 SMA and exits on a bearish crossover.",
    asset: "AAPL",
    universe: ["AAPL", "MSFT", "NVDA", "SPY"],
    timeframe: "1D",
    strategy_type: "trend",
    indicators: [
      { id: "sma_fast", name: "SMA", params: { period: 20 } },
      { id: "sma_slow", name: "SMA", params: { period: 50 } },
    ],
    entry_rules: [
      { id: "r1", indicator_a: "sma_fast", operator: "CROSS_ABOVE", indicator_b: "sma_slow" },
    ],
    exit_rules: [
      { id: "x1", indicator_a: "sma_fast", operator: "CROSS_BELOW", indicator_b: "sma_slow" },
    ],
    risk: { stop_loss_pct: 3.5, take_profit_pct: 12.0, position_size_pct: 15, max_positions: 5, allow_short: false },
    execution: { initial_capital: 100000, commission_pct: 0.05, slippage_pct: 0.05, spread_pct: 0.02, allow_fractional: true },
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "tpl_rsi_reversion",
    name: "RSI 2-Period Mean Reversion",
    description: "Larry Connors RSI-2 mean reversion strategy buying deep short-term pullbacks above 200 SMA and selling on fast bounce.",
    asset: "SPY",
    universe: ["SPY", "QQQ", "AAPL", "MSFT"],
    timeframe: "1D",
    strategy_type: "mean_reversion",
    indicators: [
      { id: "rsi_2", name: "RSI", params: { period: 2 } },
      { id: "sma_200", name: "SMA", params: { period: 200 } },
      { id: "sma_5", name: "SMA", params: { period: 5 } },
    ],
    entry_rules: [
      { id: "r1", indicator_a: "rsi_2", operator: "<", threshold: 10 },
      { id: "r2", indicator_a: "close", operator: ">", indicator_b: "sma_200" },
    ],
    exit_rules: [
      { id: "x1", indicator_a: "close", operator: ">", indicator_b: "sma_5" },
    ],
    risk: { stop_loss_pct: 5.0, take_profit_pct: 8.0, position_size_pct: 20, max_positions: 4, allow_short: false },
    execution: { initial_capital: 100000, commission_pct: 0.04, slippage_pct: 0.04, spread_pct: 0.02, allow_fractional: true },
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "tpl_bollinger_breakout",
    name: "Bollinger Band Volatility Breakout",
    description: "Enters long when price closes decisively above the 2.0-sigma upper Bollinger Band with confirming momentum.",
    asset: "NVDA",
    universe: ["NVDA", "TSLA", "AMD", "QQQ"],
    timeframe: "1D",
    strategy_type: "breakout",
    indicators: [
      { id: "bb_upper", name: "BB_UPPER", params: { period: 20, std_dev: 2.0 } },
      { id: "bb_middle", name: "BB_MIDDLE", params: { period: 20 } },
      { id: "adx", name: "ADX", params: { period: 14 } },
    ],
    entry_rules: [
      { id: "r1", indicator_a: "close", operator: "CROSS_ABOVE", indicator_b: "bb_upper" },
      { id: "r2", indicator_a: "adx", operator: ">", threshold: 25 },
    ],
    exit_rules: [
      { id: "x1", indicator_a: "close", operator: "CROSS_BELOW", indicator_b: "bb_middle" },
    ],
    risk: { stop_loss_pct: 4.0, take_profit_pct: 15.0, position_size_pct: 15, max_positions: 5, allow_short: false },
    execution: { initial_capital: 100000, commission_pct: 0.05, slippage_pct: 0.06, spread_pct: 0.03, allow_fractional: true },
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "tpl_donchian_turtle",
    name: "Turtle Trading Donchian Breakout",
    description: "Classic Richard Dennis 20-day high breakout entry with 10-day low stop exit, scaled with ATR position sizing.",
    asset: "SPY",
    universe: ["SPY", "GLD", "TLT", "USO"],
    timeframe: "1D",
    strategy_type: "breakout",
    indicators: [
      { id: "donchian_high", name: "DONCHIAN_HIGH", params: { period: 20 } },
      { id: "donchian_low", name: "DONCHIAN_LOW", params: { period: 10 } },
      { id: "atr", name: "ATR", params: { period: 20 } },
    ],
    entry_rules: [
      { id: "r1", indicator_a: "high", operator: ">=", indicator_b: "donchian_high" },
    ],
    exit_rules: [
      { id: "x1", indicator_a: "low", operator: "<=", indicator_b: "donchian_low" },
    ],
    risk: { stop_loss_pct: 4.5, take_profit_pct: 20.0, position_size_pct: 10, max_positions: 8, allow_short: false },
    execution: { initial_capital: 100000, commission_pct: 0.05, slippage_pct: 0.05, spread_pct: 0.02, allow_fractional: true },
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "tpl_india_momentum_alpha",
    name: "NSE Bluechip Trend Alpha",
    description: "Dual EMA cross with ADX trend filter tailored for NSE India large-cap equities with trailing stops.",
    asset: "RELIANCE",
    universe: ["RELIANCE", "TCS", "INFY", "HDFCBANK", "^NSEI"],
    timeframe: "1D",
    strategy_type: "trend",
    indicators: [
      { id: "ema_15", name: "EMA", params: { period: 15 } },
      { id: "ema_45", name: "EMA", params: { period: 45 } },
      { id: "adx_14", name: "ADX", params: { period: 14 } },
    ],
    entry_rules: [
      { id: "r1", indicator_a: "ema_15", operator: "CROSS_ABOVE", indicator_b: "ema_45" },
      { id: "r2", indicator_a: "adx_14", operator: ">", threshold: 22 },
    ],
    exit_rules: [
      { id: "x1", indicator_a: "ema_15", operator: "CROSS_BELOW", indicator_b: "ema_45" },
    ],
    risk: { stop_loss_pct: 3.0, take_profit_pct: 10.0, position_size_pct: 15, max_positions: 6, allow_short: false },
    execution: { initial_capital: 1000000, commission_pct: 0.03, slippage_pct: 0.05, spread_pct: 0.02, allow_fractional: true },
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "tpl_macd_confirmation",
    name: "MACD Multi-Timeframe Momentum",
    description: "Momentum confirmation system trading MACD line crosses with histogram expansion and 50 SMA trend alignment.",
    asset: "MSFT",
    universe: ["MSFT", "AAPL", "NVDA", "QQQ"],
    timeframe: "1D",
    strategy_type: "momentum",
    indicators: [
      { id: "macd", name: "MACD", params: { fast_period: 12, slow_period: 26 } },
      { id: "macd_signal", name: "MACD_SIGNAL", params: { fast_period: 12, slow_period: 26, signal_period: 9 } },
      { id: "sma_50", name: "SMA", params: { period: 50 } },
    ],
    entry_rules: [
      { id: "r1", indicator_a: "macd", operator: "CROSS_ABOVE", indicator_b: "macd_signal" },
      { id: "r2", indicator_a: "close", operator: ">", indicator_b: "sma_50" },
    ],
    exit_rules: [
      { id: "x1", indicator_a: "macd", operator: "CROSS_BELOW", indicator_b: "macd_signal" },
    ],
    risk: { stop_loss_pct: 3.5, take_profit_pct: 12.5, position_size_pct: 20, max_positions: 5, allow_short: false },
    execution: { initial_capital: 100000, commission_pct: 0.05, slippage_pct: 0.05, spread_pct: 0.02, allow_fractional: true },
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

export const SEED_STOCK_PROFILES: Record<string, StockProfile> = {
  AAPL: {
    symbol: "AAPL",
    yf_symbol: "AAPL",
    name: "Apple Inc.",
    market: "US",
    exchange: "NASDAQ",
    sector: "Technology",
    price: 232.10,
    change_1d: 1.45,
    volume_1d: 48920100,
    market_cap: 3510000000000,
    pe_ratio: 34.2,
    eps_ttm: 6.78,
    dividend_yield: 0.44,
    currency: "USD",
  },
  NVDA: {
    symbol: "NVDA",
    yf_symbol: "NVDA",
    name: "NVIDIA Corporation",
    market: "US",
    exchange: "NASDAQ",
    sector: "Technology",
    price: 138.25,
    change_1d: 2.91,
    volume_1d: 67120300,
    market_cap: 3390000000000,
    pe_ratio: 58.4,
    eps_ttm: 2.37,
    dividend_yield: 0.03,
    currency: "USD",
  },
  MSFT: {
    symbol: "MSFT",
    yf_symbol: "MSFT",
    name: "Microsoft Corporation",
    market: "US",
    exchange: "NASDAQ",
    sector: "Technology",
    price: 432.80,
    change_1d: -1.15,
    volume_1d: 19400200,
    market_cap: 3210000000000,
    pe_ratio: 36.1,
    eps_ttm: 11.98,
    dividend_yield: 0.71,
    currency: "USD",
  },
  SPY: {
    symbol: "SPY",
    yf_symbol: "SPY",
    name: "SPDR S&P 500 ETF Trust",
    market: "US",
    exchange: "NYSE",
    sector: "ETF",
    price: 588.45,
    change_1d: 2.45,
    volume_1d: 54100900,
    market_cap: 580000000000,
    pe_ratio: 27.5,
    eps_ttm: 21.40,
    dividend_yield: 1.22,
    currency: "USD",
  },
  QQQ: {
    symbol: "QQQ",
    yf_symbol: "QQQ",
    name: "Invesco QQQ Trust",
    market: "US",
    exchange: "NASDAQ",
    sector: "ETF",
    price: 509.12,
    change_1d: 4.30,
    volume_1d: 38200400,
    market_cap: 290000000000,
    pe_ratio: 31.8,
    eps_ttm: 16.02,
    dividend_yield: 0.58,
    currency: "USD",
  },
  RELIANCE: {
    symbol: "RELIANCE",
    yf_symbol: "RELIANCE.NS",
    name: "Reliance Industries Limited",
    market: "India",
    exchange: "NSE",
    sector: "Energy",
    price: 1290.90,
    change_1d: -28.10,
    volume_1d: 8450100,
    market_cap: 17450000000000,
    pe_ratio: 24.8,
    eps_ttm: 52.05,
    dividend_yield: 0.77,
    currency: "INR",
  },
  TCS: {
    symbol: "TCS",
    yf_symbol: "TCS.NS",
    name: "Tata Consultancy Services",
    market: "India",
    exchange: "NSE",
    sector: "Technology",
    price: 3840.00,
    change_1d: 24.80,
    volume_1d: 2150300,
    market_cap: 13900000000000,
    pe_ratio: 29.5,
    eps_ttm: 130.2,
    dividend_yield: 1.30,
    currency: "INR",
  },
  INFY: {
    symbol: "INFY",
    yf_symbol: "INFY.NS",
    name: "Infosys Limited",
    market: "India",
    exchange: "NSE",
    sector: "Technology",
    price: 1825.40,
    change_1d: 12.20,
    volume_1d: 5120400,
    market_cap: 7580000000000,
    pe_ratio: 28.2,
    eps_ttm: 64.7,
    dividend_yield: 1.98,
    currency: "INR",
  },
  HDFCBANK: {
    symbol: "HDFCBANK",
    yf_symbol: "HDFCBANK.NS",
    name: "HDFC Bank Limited",
    market: "India",
    exchange: "NSE",
    sector: "Financial Services",
    price: 1685.20,
    change_1d: -8.40,
    volume_1d: 14200100,
    market_cap: 12820000000000,
    pe_ratio: 18.9,
    eps_ttm: 89.15,
    dividend_yield: 1.16,
    currency: "INR",
  },
  GENUSPOWER: {
    symbol: "GENUSPOWER",
    yf_symbol: "GENUSPOWER.NS",
    name: "Genus Power Infrastructures Ltd",
    market: "India",
    exchange: "NSE",
    sector: "Capital Goods",
    price: 412.50,
    change_1d: 18.20,
    volume_1d: 1840200,
    market_cap: 124500000000,
    pe_ratio: 42.1,
    eps_ttm: 9.80,
    dividend_yield: 0.18,
    currency: "INR",
  },
  KAYNES: {
    symbol: "KAYNES",
    yf_symbol: "KAYNES.NS",
    name: "Kaynes Technology India Ltd",
    market: "India",
    exchange: "NSE",
    sector: "Technology",
    price: 5240.00,
    change_1d: 110.50,
    volume_1d: 620400,
    market_cap: 334000000000,
    pe_ratio: 84.5,
    eps_ttm: 62.0,
    dividend_yield: 0.05,
    currency: "INR",
  },
};

/**
 * Generate 252 realistic daily OHLCV bars for any ticker
 */
export function generateSyntheticBars(ticker: string, basePrice: number = 200, count: number = 252): MarketBar[] {
  const bars: MarketBar[] = [];
  const now = new Date();
  let currentPrice = basePrice;

  for (let i = count; i >= 0; i--) {
    const d = new Date(now);
    d.setDate(d.getDate() - i);
    if (d.getDay() === 0 || d.getDay() === 6) continue;

    const returnPct = (Math.sin(i * 0.12) * 0.015) + ((Math.random() - 0.48) * 0.02);
    const prevClose = currentPrice;
    currentPrice = Math.max(1, Number((currentPrice * (1 + returnPct)).toFixed(2)));

    const high = Number((Math.max(prevClose, currentPrice) * (1 + Math.random() * 0.012)).toFixed(2));
    const low = Number((Math.min(prevClose, currentPrice) * (1 - Math.random() * 0.012)).toFixed(2));
    const open = Number((prevClose * (1 + (Math.random() - 0.5) * 0.006)).toFixed(2));
    const volume = Math.round(1000000 + Math.random() * 4000000);

    bars.push({
      date: d.toISOString().split("T")[0],
      open,
      high,
      low,
      close: currentPrice,
      volume,
      return: returnPct,
      drawdown: 0,
      volatility: 0.15,
      indicators: {
        sma_20: Number((currentPrice * (1 + Math.sin(i * 0.08) * 0.01)).toFixed(2)),
        sma_50: Number((currentPrice * (1 + Math.cos(i * 0.05) * 0.02)).toFixed(2)),
        rsi_14: Number((50 + Math.sin(i * 0.2) * 25).toFixed(1)),
        macd: Number((Math.sin(i * 0.15) * 2.5).toFixed(2)),
        macd_signal: Number((Math.sin((i - 1) * 0.15) * 2.2).toFixed(2)),
        macd_hist: Number((Math.sin(i * 0.15) * 0.5).toFixed(2)),
        bb_upper: Number((currentPrice * 1.04).toFixed(2)),
        bb_lower: Number((currentPrice * 0.96).toFixed(2)),
        atr_14: Number((currentPrice * 0.022).toFixed(2)),
      },
    });
  }
  return bars;
}

export const SEED_BACKTESTS: BacktestResult[] = [
  {
    id: "bt_dual_ma_aapl",
    strategy_id: "tpl_sma_crossover",
    strategy_name: "Dual Moving Average Crossover",
    ticker: "AAPL",
    asset: "AAPL",
    benchmark: "SPY",
    start_date: "2023-01-01",
    end_date: "2024-01-01",
    status: "COMPLETED",
    metrics: {
      total_return: 0.2834,
      cagr: 0.1312,
      annualized_return: 0.134,
      annualized_volatility: 0.158,
      sharpe_ratio: 1.76,
      sortino_ratio: 2.41,
      calmar_ratio: 0.88,
      max_drawdown: 14.93,
      max_drawdown_duration: 37,
      win_rate: 61.2,
      loss_rate: 38.8,
      profit_factor: 2.08,
      expectancy: 1.84,
      num_trades: 48,
      winning_trades: 29,
      losing_trades: 19,
      avg_trade_return: 1.24,
      avg_win: 3.42,
      avg_loss: 1.96,
      avg_holding_period: 14.2,
      turnover: 1.45,
      total_fees: 142.5,
      gross_pnl: 28482.5,
      net_pnl: 28340,
      best_trade: 8.5,
      worst_trade: -3.8,
      alpha: 0.065,
      beta: 0.95,
      information_ratio: 1.25,
      tracking_error: 0.052,
    },
    equity_curve: Array.from({ length: 50 }, (_, i) => ({
      date: `2023-${String(Math.floor(i / 4) + 1).padStart(2, "0")}-${String((i % 28) + 1).padStart(2, "0")}`,
      portfolio_value: Math.round(100000 * (1 + (i / 50) * 0.2834 + Math.sin(i) * 0.015)),
      benchmark_value: Math.round(100000 * (1 + (i / 50) * 0.182 + Math.sin(i * 0.8) * 0.01)),
      cash: Math.round(15000 + Math.cos(i) * 5000),
      drawdown: Math.max(0, Number((Math.sin(i * 0.3) * 6).toFixed(2))),
      returns: 0.005,
      benchmark_returns: 0.003,
    })),
    trades: [
      {
        id: "tr_1",
        ticker: "AAPL",
        direction: "LONG",
        entry_date: "2023-02-10",
        exit_date: "2023-03-05",
        entry_price: 151.2,
        exit_price: 165.4,
        quantity: 600,
        gross_pnl: 8520,
        fees: 15.2,
        net_pnl: 8504.8,
        return_pct: 9.39,
        holding_period_bars: 17,
        exit_reason: "TAKE_PROFIT",
        mae: -1.2,
        mfe: 10.4,
      },
      {
        id: "tr_2",
        ticker: "AAPL",
        direction: "LONG",
        entry_date: "2023-04-12",
        exit_date: "2023-05-18",
        entry_price: 162.1,
        exit_price: 174.8,
        quantity: 550,
        gross_pnl: 6985,
        fees: 14.5,
        net_pnl: 6970.5,
        return_pct: 7.83,
        holding_period_bars: 26,
        exit_reason: "SIGNAL_EXIT",
        mae: -2.1,
        mfe: 8.9,
      },
    ],
    monthly_returns: [
      { year: 2023, YTD: 28.34, Jan: 4.2, Feb: -1.1, Mar: 3.5, Apr: 1.8, May: 4.6, Jun: 2.1, Jul: 3.2, Aug: -2.4, Sep: -1.5, Oct: 3.8, Nov: 5.2, Dec: 2.9 },
    ],
    logs: ["Simulation started", "Generated 48 trades", "Simulation complete"],
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "bt_india_alpha_rel",
    strategy_id: "tpl_india_momentum_alpha",
    strategy_name: "NSE Bluechip Trend Alpha",
    ticker: "RELIANCE",
    asset: "RELIANCE",
    benchmark: "^NSEI",
    start_date: "2023-01-01",
    end_date: "2024-01-01",
    status: "COMPLETED",
    metrics: {
      total_return: 0.3421,
      cagr: 0.1842,
      annualized_return: 0.191,
      annualized_volatility: 0.174,
      sharpe_ratio: 1.88,
      sortino_ratio: 2.65,
      calmar_ratio: 1.12,
      max_drawdown: 12.4,
      max_drawdown_duration: 28,
      win_rate: 64.5,
      loss_rate: 35.5,
      profit_factor: 2.35,
      expectancy: 2.12,
      num_trades: 42,
      winning_trades: 27,
      losing_trades: 15,
      avg_trade_return: 1.48,
      avg_win: 3.85,
      avg_loss: 1.82,
      avg_holding_period: 16.0,
      turnover: 1.32,
      total_fees: 1120.0,
      gross_pnl: 343220,
      net_pnl: 342100,
      best_trade: 9.8,
      worst_trade: -2.9,
      alpha: 0.082,
      beta: 0.88,
      information_ratio: 1.42,
      tracking_error: 0.048,
    },
    equity_curve: Array.from({ length: 50 }, (_, i) => ({
      date: `2023-${String(Math.floor(i / 4) + 1).padStart(2, "0")}-${String((i % 28) + 1).padStart(2, "0")}`,
      portfolio_value: Math.round(1000000 * (1 + (i / 50) * 0.3421 + Math.sin(i * 1.1) * 0.018)),
      benchmark_value: Math.round(1000000 * (1 + (i / 50) * 0.195 + Math.sin(i * 0.9) * 0.012)),
      cash: Math.round(120000 + Math.cos(i) * 30000),
      drawdown: Math.max(0, Number((Math.sin(i * 0.25) * 5.2).toFixed(2))),
      returns: 0.006,
      benchmark_returns: 0.0035,
    })),
    trades: [
      {
        id: "tr_in_1",
        ticker: "RELIANCE",
        direction: "LONG",
        entry_date: "2023-01-18",
        exit_date: "2023-02-22",
        entry_price: 1180.0,
        exit_price: 1295.0,
        quantity: 800,
        gross_pnl: 92000,
        fees: 250.0,
        net_pnl: 91750.0,
        return_pct: 9.75,
        holding_period_bars: 24,
        exit_reason: "TAKE_PROFIT",
        mae: -1.0,
        mfe: 10.8,
      },
    ],
    monthly_returns: [
      { year: 2023, YTD: 34.21, Jan: 5.1, Feb: 1.4, Mar: 2.8, Apr: 4.2, May: -1.2, Jun: 3.9, Jul: 4.5, Aug: 1.1, Sep: -2.1, Oct: 4.8, Nov: 6.1, Dec: 3.6 },
    ],
    logs: ["Simulation started", "Generated 42 trades", "Simulation complete"],
    created_at: "2024-01-01T00:00:00Z",
  },
];
