"use client";

import React from "react";
import { Info, GitMerge, ArrowUpRight, ArrowDownRight } from "lucide-react";
import { BacktestResult } from "@/types";

interface AnalyticsAttributionTabProps {
  selectedBacktests: BacktestResult[];
}

export default function AnalyticsAttributionTab({
  selectedBacktests,
}: AnalyticsAttributionTabProps) {
  const brinsonDecomposition = [
    { component: "Asset Allocation Effect", returnPct: "+4.18%", description: "Value added from over/under weighting outperforming sectors/assets" },
    { component: "Stock / Signal Selection Effect", returnPct: "+5.62%", description: "Excess alpha generated by timing entry/exits within each asset" },
    { component: "Interaction / Synergy Effect", returnPct: "-1.59%", description: "Combined cross-interaction between active weights and individual returns" },
    { component: "Net Total Active Excess Return", returnPct: "+8.21%", description: "Total strategy outperformance over benchmark SPY" },
  ];

  const sectorAttributions = [
    { sector: "Information Technology", weight: "38.4%", benchmarkWeight: "29.2%", activeReturn: "+14.2%", contribution: "+4.12%" },
    { sector: "Consumer Discretionary", weight: "18.2%", benchmarkWeight: "10.4%", activeReturn: "+8.6%", contribution: "+1.94%" },
    { sector: "Communication Services", weight: "14.5%", benchmarkWeight: "8.8%", activeReturn: "+6.8%", contribution: "+1.42%" },
    { sector: "Financials", weight: "12.1%", benchmarkWeight: "13.1%", activeReturn: "-2.4%", contribution: "-0.28%" },
    { sector: "Health Care", weight: "9.8%", benchmarkWeight: "12.4%", activeReturn: "+3.1%", contribution: "+0.84%" },
    { sector: "Cash / Margin", weight: "7.0%", benchmarkWeight: "0.0%", activeReturn: "+0.2%", contribution: "+0.17%" },
  ];

  return (
    <div className="space-y-4">
      {/* Brinson-Fachler Decomposition Table */}
      <div className="bg-[#090D14] border border-[#1E2530] rounded-lg p-4 space-y-3">
        <div className="pb-2 border-b border-[#1E2530]">
          <span className="font-semibold text-white text-xs tracking-tight">
            Brinson-Fachler Performance Attribution Decomposition
          </span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs font-mono">
            <thead>
              <tr className="border-b border-[#1E2530] text-[10px] text-slate-400 uppercase font-sans">
                <th className="py-2">Attribution Component</th>
                <th className="py-2">Return Impact</th>
                <th className="py-2">Quantitative Methodology</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#1E2530]/50">
              {brinsonDecomposition.map((item, idx) => (
                <tr key={item.component} className={idx === brinsonDecomposition.length - 1 ? "bg-[#111622] font-bold" : "hover:bg-[#111622]/50"}>
                  <td className="py-2.5 font-bold text-white font-sans">{item.component}</td>
                  <td className={`py-2.5 font-bold ${item.returnPct.startsWith("+") ? "text-[#10B981]" : "text-[#EF4444]"}`}>
                    {item.returnPct}
                  </td>
                  <td className="py-2.5 text-slate-400 font-sans text-[11px]">{item.description}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Sector Attribution Breakdown */}
      <div className="bg-[#090D14] border border-[#1E2530] rounded-lg p-4 space-y-3">
        <div className="pb-2 border-b border-[#1E2530]">
          <span className="font-semibold text-white text-xs tracking-tight">
            Sector & Asset Class Attribution Breakdown
          </span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs font-mono">
            <thead>
              <tr className="border-b border-[#1E2530] text-[10px] text-slate-400 uppercase font-sans">
                <th className="py-2">Sector / Asset Class</th>
                <th className="py-2 text-right">Portfolio Weight</th>
                <th className="py-2 text-right">Benchmark Weight</th>
                <th className="py-2 text-right">Active Return</th>
                <th className="py-2 text-right">Net Contribution</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#1E2530]/50">
              {sectorAttributions.map((s) => (
                <tr key={s.sector} className="hover:bg-[#111622]/50">
                  <td className="py-2.5 font-medium text-slate-200 font-sans">{s.sector}</td>
                  <td className="py-2.5 text-right text-white">{s.weight}</td>
                  <td className="py-2.5 text-right text-slate-400">{s.benchmarkWeight}</td>
                  <td className={`py-2.5 text-right font-semibold ${s.activeReturn.startsWith("+") ? "text-[#10B981]" : "text-[#EF4444]"}`}>
                    {s.activeReturn}
                  </td>
                  <td className={`py-2.5 text-right font-bold ${s.contribution.startsWith("+") ? "text-[#10B981]" : "text-[#EF4444]"}`}>
                    {s.contribution}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
